### ISSUE TITLE
Dreamweb - JS port

### ISSUE THREAD

**Issue by K4T** [DrummerSi/dreamweb-assets#1]
Hello,

Some time ago I ported almost 95% of the game into JavaScript :). If you are interested I can show you my work.

**Comment by DrummerSi** [comment]
**I'd LOVE to see it!**

My original intent was to make JS web version of the game by exporting everything from the game: assets, rooms, paths, text, audio.. I got a fairway through, but can't 100% crack the binary algorithm used, so some assets are still corrupt.

**Comment by K4T** [comment]
How can I PM you?

**Comment by DrummerSi** [comment]
Feel free to DM me on Twitter: @Drummer_si
